using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

class Program
{
    static string SanitizeFileName(string fileName)
    {
        // Invalid characters across all operating systems
        // Windows: < > : " / \ | ? *
        // Linux/macOS: / and null character
        // To ensure cross-platform compatibility, replace all known invalid chars
        char[] invalidChars = Path.GetInvalidFileNameChars();
        var sanitized = new StringBuilder(fileName);

        // Replace all invalid characters with underscore
        foreach (char c in invalidChars)
        {
            sanitized.Replace(c, '_');
        }

        // Also replace any additional problematic characters that might cause issues
        // Handle control characters (0-31) and DEL (127)
        for (int i = 0; i < sanitized.Length; i++)
        {
            if (char.IsControl(sanitized[i]) || sanitized[i] == 127)
            {
                sanitized[i] = '_';
            }
        }

        // Trim leading/trailing dots, spaces, and other whitespace
        string result = sanitized.ToString().Trim('.', ' ', '\t');

        // Ensure the filename is not empty
        if (string.IsNullOrWhiteSpace(result))
        {
            result = "transcript";
        }

        // Limit filename length to prevent filesystem issues (typically 255 chars)
        // Leave room for extension (.txt = 4 chars)
        if (result.Length > 200)
        {
            result = result.Substring(0, 200);
        }

        return result;
    }

    static async Task Main(string[] args)
    {
        Console.WriteLine("YouTube Transcript Extractor");
        Console.WriteLine("No API key or authentication required!");
        Console.WriteLine();

        Console.WriteLine("Enter YouTube video URL or ID:");
        var input = Console.ReadLine()?.Trim();

        if (string.IsNullOrEmpty(input))
        {
            Console.WriteLine("No input provided.");
            return;
        }

        // Parse YouTube video ID
        string videoId;
        try
        {
            videoId = YouTubeApiClient.ExtractVideoId(input);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Invalid YouTube URL or ID: {ex.Message}");
            return;
        }

        try
        {
            // Initialize API client (no authentication needed)
            var apiClient = new YouTubeApiClient();

            Console.WriteLine("Fetching video information...");

            // Get video information
            var video = await apiClient.GetVideoInfoAsync(videoId);
            Console.WriteLine($"Video title: {video.Title}");
            Console.WriteLine();

            // List available captions
            Console.WriteLine("Fetching available captions...");
            var captions = await apiClient.ListCaptionsAsync(videoId);

            if (captions.Count == 0)
            {
                Console.WriteLine("No captions found for this video.");
                return;
            }

            Console.WriteLine($"Found {captions.Count} caption track(s):");
            foreach (var caption in captions)
            {
                var typeLabel = caption.IsAutoGenerated ? "Auto-generated" : "Manual";
                Console.WriteLine($"  - {caption.Language} ({caption.Name}) - {typeLabel}");
            }
            Console.WriteLine();

            // Download each caption track
            foreach (var captionInfo in captions)
            {
                try
                {
                    Console.WriteLine($"Downloading {captionInfo.Language} ({captionInfo.Name})...");
                    Console.WriteLine($"Caption URL: {captionInfo.BaseUrl}");

                    string transcriptText = await apiClient.DownloadTranscriptAsTextAsync(captionInfo.BaseUrl);

                    if (string.IsNullOrWhiteSpace(transcriptText))
                    {
                        Console.WriteLine($"Warning: No transcript content found for {captionInfo.Language}.");
                        Console.WriteLine("This might indicate an issue with the transcript format or parsing.");
                        continue;
                    }

                    Console.WriteLine($"Extracted {transcriptText.Split('\n').Length} lines of transcript text.");

                    var typeSuffix = captionInfo.IsAutoGenerated ? " (auto-generated)" : "";
                    var fileName = $"{video.Title}-{captionInfo.Language}-{captionInfo.Name}{typeSuffix}";
                    var sanitizedFileName = SanitizeFileName(fileName);
                    var outputFile = $"{sanitizedFileName}.txt";

                    await File.WriteAllTextAsync(outputFile, transcriptText);
                    Console.WriteLine($"Transcript saved to {outputFile}");
                    Console.WriteLine();
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error downloading caption {captionInfo.Language}: {ex.Message}");
                    if (ex.InnerException != null)
                    {
                        Console.WriteLine($"  Inner exception: {ex.InnerException.Message}");
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
            if (ex.InnerException != null)
            {
                Console.WriteLine($"Inner exception: {ex.InnerException.Message}");
            }
            Console.WriteLine($"Stack Trace: {ex.StackTrace}");
        }
    }
}
